### ISSUE TITLE
Fix local `load-data` flow

### ISSUE THREAD

**Issue by andrew-wm-arthur** [nautobot/nautobot-plugin-version-control#102]
The "load-data" workflow described in the README currently has a bug with its Redis configuration

**Comment by andrew-wm-arthur** [comment]
stack trace for tracking:
```
Installed 13604 object(s) from 1 fixture(s)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 615, in _connect
    raise err
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/backends/redis.py", line 118, in reconnect_on_error
    yield
  File "/usr/local/lib/python3.6/site-packages/celery/backends/redis.py", line 168, in _consume_from
    self._pubsub.subscribe(key)
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 3580, in subscribe
    ret_val = self.execute_command('SUBSCRIBE', *iterkeys(new_channels))
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 3468, in execute_command
    self.shard_hint
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 99 connecting to localhost:6379. Cannot assign requested address.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 615, in _connect
    raise err
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/kombu/connection.py", line 448, in _reraise_as_library_errors
    yield
  File "/usr/local/lib/python3.6/site-packages/celery/app/base.py", line 766, in send_task
    self.backend.on_task_call(P, task_id)
  File "/usr/local/lib/python3.6/site-packages/celery/backends/redis.py", line 364, in on_task_call
    self.result_consumer.consume_from(task_id)
  File "/usr/local/lib/python3.6/site-packages/celery/backends/redis.py", line 160, in consume_from
    return self.start(task_id)
  File "/usr/local/lib/python3.6/site-packages/celery/backends/redis.py", line 138, in start
    self._consume_from(initial_task_id)
  File "/usr/local/lib/python3.6/site-packages/celery/backends/redis.py", line 168, in _consume_from
    self._pubsub.subscribe(key)
  File "/usr/local/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.6/site-packages/celery/backends/redis.py", line 121, in reconnect_on_error
    self._ensure(self._reconnect_pubsub, ())
  File "/usr/local/lib/python3.6/site-packages/celery/backends/redis.py", line 378, in ensure
    **retry_policy)
  File "/usr/local/lib/python3.6/site-packages/kombu/utils/functional.py", line 313, in retry_over_time
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/backends/redis.py", line 106, in _reconnect_pubsub
    metas = self.backend.client.mget(self.subscribed_to)
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 1671, in mget
    return self.execute_command('MGET', *args, **options)
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 99 connecting to localhost:6379. Cannot assign requested address.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/nautobot-server", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/nautobot/core/cli.py", line 62, in main
    initializer=_configure_settings,  # Called after defaults
  File "/usr/local/lib/python3.6/site-packages/nautobot/core/runner/runner.py", line 266, in run_app
    management.execute_from_command_line([runner_name, command] + command_args)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/loaddata.py", line 72, in handle
    self.loaddata(fixture_labels)
  File "/usr/local/lib/python3.6/site-packages/cacheops/transaction.py", line 76, in __exit__
    self._no_monkey.__exit__(self, exc_type, exc_value, traceback)
  File "/usr/local/lib/python3.6/site-packages/django/db/transaction.py", line 276, in __exit__
    connection.set_autocommit(True)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 420, in set_autocommit
    self.run_and_clear_commit_hooks()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 651, in run_and_clear_commit_hooks
    func()
  File "/usr/local/lib/python3.6/site-packages/nautobot/extras/signals.py", line 114, in <lambda>
    transaction.on_commit(lambda: provision_field.delay(instance.pk, pk_set))
  File "/usr/local/lib/python3.6/site-packages/celery/app/task.py", line 422, in delay
    return self.apply_async(args, kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/task.py", line 576, in apply_async
    **options
  File "/usr/local/lib/python3.6/site-packages/celery/app/base.py", line 767, in send_task
    amqp.send_task_message(P, name, message, **options)
  File "/usr/local/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.6/site-packages/kombu/connection.py", line 452, in _reraise_as_library_errors
    raise ConnectionError(str(exc)) from exc
kombu.exceptions.OperationalError: Error 99 connecting to localhost:6379. Cannot assign requested address.
ERROR: 1
```

**Comment by jathanism** [comment]
Per our Slack chat, check out `development/nautobot_config.py` in the core Nautobot repo for an example of a minimal configuration that can be used for testing within Docker Compose. Also check out `dev.env` file in that same directory to see how the environment variables get passed in.
