### ISSUE TITLE
Error when trying to access http://167.71.81.237:8080/api/plugins/dolt/branches/ and http://167.71.81.237:8080/api/plugins/dolt/branches/ on demo instance

### ISSUE THREAD

**Issue by tim-fiola** [nautobot/nautobot-plugin-version-control#92]
I get the following exceptions, respectively, whey trying to access
* http://167.71.81.237:8080/api/plugins/dolt/branches/
* http://167.71.81.237:8080/api/plugins/dolt/commits/

```
Environment:


Request Method: GET
Request URL: http://167.71.81.237:8080/api/plugins/dolt/branches/

Django Version: 3.1.13
Python Version: 3.8.10
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.humanize',
 'cacheops',
 'corsheaders',
 'django_filters',
 'django_jinja',
 'django_tables2',
 'django_prometheus',
 'mptt',
 'rest_framework',
 'social_django',
 'taggit',
 'timezone_field',
 'nautobot.core',
 'nautobot.circuits',
 'nautobot.dcim',
 'nautobot.ipam',
 'nautobot.extras',
 'nautobot.tenancy',
 'nautobot.users',
 'nautobot.utilities',
 'nautobot.virtualization',
 'django_rq',
 'drf_yasg',
 'graphene_django',
 'health_check',
 'health_check.db',
 'health_check.cache',
 'health_check.storage',
 'dolt.NautobotDolt']
Installed Middleware:
['django_prometheus.middleware.PrometheusBeforeMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'nautobot.core.middleware.ExceptionHandlingMiddleware',
 'nautobot.core.middleware.RemoteUserMiddleware',
 'nautobot.core.middleware.ExternalAuthMiddleware',
 'nautobot.core.middleware.APIVersionMiddleware',
 'nautobot.core.middleware.ObjectChangeMiddleware',
 'django_prometheus.middleware.PrometheusAfterMiddleware',
 'dolt.middleware.dolt_health_check_intercept_middleware',
 'dolt.middleware.DoltBranchMiddleware',
 'dolt.middleware.DoltAutoCommitMiddleware']



Traceback (most recent call last):
  File "/opt/nautobot/.cache/pypoetry/virtualenvs/dolt-KRum6REo-py3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/nautobot/.cache/pypoetry/virtualenvs/dolt-KRum6REo-py3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 171, in _get_response
    response = middleware_method(request, callback, callback_args, callback_kwargs)
  File "/opt/nautobot/nautobot-plugin-workflow-dolt/dolt/middleware.py", line 62, in process_view
    return view_func(request, *view_args, **view_kwargs)
  File "/opt/nautobot/.cache/pypoetry/virtualenvs/dolt-KRum6REo-py3.8/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/nautobot/.cache/pypoetry/virtualenvs/dolt-KRum6REo-py3.8/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/nautobot/.cache/pypoetry/virtualenvs/dolt-KRum6REo-py3.8/lib/python3.8/site-packages/nautobot/core/api/views.py", line 196, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/opt/nautobot/.cache/pypoetry/virtualenvs/dolt-KRum6REo-py3.8/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/opt/nautobot/.cache/pypoetry/virtualenvs/dolt-KRum6REo-py3.8/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/nautobot/.cache/pypoetry/virtualenvs/dolt-KRum6REo-py3.8/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/opt/nautobot/.cache/pypoetry/virtualenvs/dolt-KRum6REo-py3.8/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/nautobot/.cache/pypoetry/virtualenvs/dolt-KRum6REo-py3.8/lib/python3.8/site-packages/rest_framework/mixins.py", line 40, in list
    page = self.paginate_queryset(queryset)
  File "/opt/nautobot/.cache/pypoetry/virtualenvs/dolt-KRum6REo-py3.8/lib/python3.8/site-packages/rest_framework/generics.py", line 171, in paginate_queryset
    return self.paginator.paginate_queryset(queryset, self.request, view=self)
  File "/opt/nautobot/.cache/pypoetry/virtualenvs/dolt-KRum6REo-py3.8/lib/python3.8/site-packages/nautobot/core/api/pagination.py", line 32, in paginate_queryset
    return list(queryset[self.offset : self.offset + self.limit])  # noqa: E203
  File "/opt/nautobot/.cache/pypoetry/virtualenvs/dolt-KRum6REo-py3.8/lib/python3.8/site-packages/django/db/models/query.py", line 269, in __len__
    self._fetch_all()
  File "/opt/nautobot/.cache/pypoetry/virtualenvs/dolt-KRum6REo-py3.8/lib/python3.8/site-packages/cacheops/query.py", line 273, in _fetch_all
    return self._no_monkey._fetch_all(self)
  File "/opt/nautobot/.cache/pypoetry/virtualenvs/dolt-KRum6REo-py3.8/lib/python3.8/site-packages/django/db/models/query.py", line 1310, in _fetch_all
    self._prefetch_related_objects()
  File "/opt/nautobot/.cache/pypoetry/virtualenvs/dolt-KRum6REo-py3.8/lib/python3.8/site-packages/django/db/models/query.py", line 814, in _prefetch_related_objects
    prefetch_related_objects(self._result_cache, *self._prefetch_related_lookups)
  File "/opt/nautobot/.cache/pypoetry/virtualenvs/dolt-KRum6REo-py3.8/lib/python3.8/site-packages/django/db/models/query.py", line 1697, in prefetch_related_objects
    raise AttributeError("Cannot find '%s' on %s object, '%s' is an invalid "

Exception Type: AttributeError at /api/plugins/dolt/branches/
Exception Value: Cannot find 'tags' on Branch object, 'tags' is an invalid parameter to prefetch_related()

```

```
Environment:


Request Method: GET
Request URL: http://167.71.81.237:8080/api/plugins/dolt/commits/

Django Version: 3.1.13
Python Version: 3.8.10
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.humanize',
 'cacheops',
 'corsheaders',
 'django_filters',
 'django_jinja',
 'django_tables2',
 'django_prometheus',
 'mptt',
 'rest_framework',
 'social_django',
 'taggit',
 'timezone_field',
 'nautobot.core',
 'nautobot.circuits',
 'nautobot.dcim',
 'nautobot.ipam',
 'nautobot.extras',
 'nautobot.tenancy',
 'nautobot.users',
 'nautobot.utilities',
 'nautobot.virtualization',
 'django_rq',
 'drf_yasg',
 'graphene_django',
 'health_check',
 'health_check.db',
 'health_check.cache',
 'health_check.storage',
 'dolt.NautobotDolt']
Installed Middleware:
['django_prometheus.middleware.PrometheusBeforeMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'nautobot.core.middleware.ExceptionHandlingMiddleware',
 'nautobot.core.middleware.RemoteUserMiddleware',
 'nautobot.core.middleware.ExternalAuthMiddleware',
 'nautobot.core.middleware.APIVersionMiddleware',
 'nautobot.core.middleware.ObjectChangeMiddleware',
 'django_prometheus.middleware.PrometheusAfterMiddleware',
 'dolt.middleware.dolt_health_check_intercept_middleware',
 'dolt.middleware.DoltBranchMiddleware',
 'dolt.middleware.DoltAutoCommitMiddleware']



Traceback (most recent call last):
  File "/opt/nautobot/.cache/pypoetry/virtualenvs/dolt-KRum6REo-py3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/nautobot/.cache/pypoetry/virtualenvs/dolt-KRum6REo-py3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 171, in _get_response
    response = middleware_method(request, callback, callback_args, callback_kwargs)
  File "/opt/nautobot/nautobot-plugin-workflow-dolt/dolt/middleware.py", line 62, in process_view
    return view_func(request, *view_args, **view_kwargs)
  File "/opt/nautobot/.cache/pypoetry/virtualenvs/dolt-KRum6REo-py3.8/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/nautobot/.cache/pypoetry/virtualenvs/dolt-KRum6REo-py3.8/lib/python3.8/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/nautobot/.cache/pypoetry/virtualenvs/dolt-KRum6REo-py3.8/lib/python3.8/site-packages/nautobot/core/api/views.py", line 196, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/opt/nautobot/.cache/pypoetry/virtualenvs/dolt-KRum6REo-py3.8/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/opt/nautobot/.cache/pypoetry/virtualenvs/dolt-KRum6REo-py3.8/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/nautobot/.cache/pypoetry/virtualenvs/dolt-KRum6REo-py3.8/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/opt/nautobot/.cache/pypoetry/virtualenvs/dolt-KRum6REo-py3.8/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/nautobot/.cache/pypoetry/virtualenvs/dolt-KRum6REo-py3.8/lib/python3.8/site-packages/rest_framework/mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "/opt/nautobot/.cache/pypoetry/virtualenvs/dolt-KRum6REo-py3.8/lib/python3.8/site-packages/rest_framework/generics.py", line 150, in filter_queryset
    queryset = backend().filter_queryset(self.request, queryset, self)
  File "/opt/nautobot/.cache/pypoetry/virtualenvs/dolt-KRum6REo-py3.8/lib/python3.8/site-packages/django_filters/rest_framework/backends.py", line 90, in filter_queryset
    filterset = self.get_filterset(request, queryset, view)
  File "/opt/nautobot/.cache/pypoetry/virtualenvs/dolt-KRum6REo-py3.8/lib/python3.8/site-packages/django_filters/rest_framework/backends.py", line 31, in get_filterset
    filterset_class = self.get_filterset_class(view, queryset)
  File "/opt/nautobot/.cache/pypoetry/virtualenvs/dolt-KRum6REo-py3.8/lib/python3.8/site-packages/django_filters/rest_framework/backends.py", line 64, in get_filterset_class
    assert issubclass(queryset.model, filterset_model), \

Exception Type: AssertionError at /api/plugins/dolt/commits/
Exception Value: FilterSet model <class 'dolt.models.Commit'> does not match queryset model <class 'dolt.models.Branch'>
```

**Comment by VinaiRachakonda** [comment]
This should now be fixed with the recent deploy of the demo instance
